Issue-88098: Extract label related utils from scripts
Goldspear/pytorch pull request #2
Opened 2023-02-06 14:32 UTC by Goldspear

Fixes #88098 

## Context

This is the 2nd of the 3 PRs to address issue-88098.

## What Changed
1. Extract comment related utils from trymerge.py to github_utils.py
2. Extract label related utils from trymerge.py and check_labels.py to label_utils.py

## Note to Reviewers
Due to higher degree of complexity involved to extract GitHubPR class, it's worth having a separate issue to handle that part of refactoring. This issue only focusing on refactoring where necessary to ship the functional diff.

2023-02-06 23:37 UTC, ZainRizvi requested changes
This one looks good for the most part. It's moving around enough pieces though that it would be good to validate the trymerge functionality in the private fork like we did with the other PR

2023-02-06 23:37 UTC, ZainRizvi commented on .github/scripts/check_labels.py
> -def add_comment(pr: GitHubPR) -> None:
We discussed not requiring trymerge.py to add this comment, right? So this one could stay behind

2023-02-06 23:37 UTC, ZainRizvi commented on .github/scripts/check_labels.py
> -def delete_comments(pr: GitHubPR) -> None:
And since trymerge.py won't be adding comments, we don't need it to take on the deleting functionality either

2023-02-09 16:20 UTC, ZainRizvi requested changes

2023-02-09 16:20 UTC, ZainRizvi commented on .github/scripts/check_labels.py
> +def delete_all_label_err_comments(pr: "GitHubPR") -> None:
nit: In these kind of refactoring projects, leaving the method name unchanged would make the diff easier to review & help the reviewer validate bugs didn't accidentally creep in :) 

While the function renames are def nice, saving them for a separate refactor PR would let a reviewer give you faster feedback on this one

2023-02-09 16:20 UTC, ZainRizvi commented on .github/scripts/label_utils.py
> +LABEL_ERR_MSG = f"""# {LABEL_ERR_MSG_TITLE}\n
the `\n` shouldn't be here if you're changing to a multiline string format

2023-02-09 16:20 UTC, ZainRizvi commented on .github/scripts/label_utils.py
> +
One too many line breaks here.

2023-02-09 16:20 UTC, ZainRizvi commented on .github/scripts/github_utils.py
> +def gh_fetch_json_any(
This function appears to be an internal-only to this file, so we could stick with the original name `_fetch_json_any` (the `_` prefix indicates the method is private)

2023-02-09 16:20 UTC, ZainRizvi commented on .github/scripts/github_utils.py
> +def gh_post_delete_comment(org: str, repo: str, comment_id: int) -> None:
Nothings being `POST`ed here 

```suggestion
def gh_delete_comment(org: str, repo: str, comment_id: int) -> None:
```

2023-02-10 14:50 UTC, Goldspear commented on .github/scripts/check_labels.py
> +def delete_all_label_err_comments(pr: "GitHubPR") -> None:
That's a great tip! Noted for future PRs :)

2023-02-10 16:31 UTC, ZainRizvi approved these changes
Looking good!

2023-02-12 16:06 UTC, closed without merging